---

- name: Add official Docker repository on Fedora systems
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/fedora/gpg
  become: true

- name: Install packages required for ansible.builtin.dnf on Fedora systems
  ansible.builtin.dnf:
    name: python3-dnf
    update_cache: true
  become: true

- name: Install Docker packages on Fedora systems
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  become: true

- name: Install packages required for community.docker on Fedora systems
  ansible.builtin.dnf:
    name:
      - python3-docker
      - python3-pyyaml
    update_cache: true
  become: true
