---

- name: Add official Docker repository on RHEL-based systems
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
  become: true

- name: Install packages required for ansible.builtin.dnf on RHEL-based systems
  ansible.builtin.dnf:
    name: python3-dnf
    update_cache: true
  become: true

- name: Install Docker packages on RHEL-based systems
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  become: true

- name: Enable EPEL repository on RHEL-based systems
  ansible.builtin.dnf:
    name: epel-release
    update_cache: true
  become: true

- name: Install packages required for community.docker on RHEL-based systems
  ansible.builtin.dnf:
    name:
      - python3-docker
      - python3-pyyaml
    update_cache: true
  become: true
