---

- name: Install Docker on RHEL-based systems
  import_tasks: install-rhel-based.yml
  when: ansible_facts['distribution'] == 'CentOS' or
        ansible_facts['distribution'] == 'AlmaLinux' or
        ansible_facts['distribution'] == 'Rocky' or
        ansible_facts['distribution'] == 'OracleLinux'

- name: Install Docker on Fedora systems
  import_tasks: install-fedora.yml
  when: ansible_facts['distribution'] == 'Fedora'

- name: Install Docker on Debian systems
  import_tasks: install-debian.yml
  when: ansible_facts['distribution'] == 'Debian'

- name: Install Docker on Ubuntu systems
  import_tasks: install-ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Add current user to docker group
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: true
  become: true

- name: Create Docker configuration directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
  become: true

- name: Add Docker daemon configuration on SELinux systems
  ansible.builtin.copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
  become: true
  when: ansible_facts['selinux']['status'] == 'enabled'

- name: Start and enable docker.service
  ansible.builtin.systemd:
    name: docker.service
    enabled: true
    state: started
  become: true

- name: Start and enable containerd.service
  ansible.builtin.systemd:
    name: containerd.service
    enabled: true
    state: started
  become: true
