---

- name: Verify Docker is installed and running
  hosts:
    - almalinux8
    - almalinux9
    - fedora36
    - fedora37
    - debian10
    - debian11
    - ubuntu2004
    - ubuntu2204
  tasks:

    - name: Ensure python3-apt is installed on Apt systems for ansible.builtin.package_facts
      ansible.builtin.apt:
        name: python3-apt
      become: true
      when: ansible_facts['pkg_mgr'] == 'apt'

    - name: Gather facts about packages
      ansible.builtin.package_facts:
        manager: auto

    - name: Assert docker-ce is installed
      ansible.builtin.assert:
        that: "'docker-ce' in ansible_facts['packages']"
        success_msg: docker-ce is installed.
        fail_msg: docker-ce is not installed.

    - name: Assert docker-ce-cli is installed
      ansible.builtin.assert:
        that: "'docker-ce-cli' in ansible_facts['packages']"
        success_msg: docker-ce-cli is installed.
        fail_msg: docker-ce-cli is not installed.

    - name: Assert containerd.io is installed
      ansible.builtin.assert:
        that: "'containerd.io' in ansible_facts['packages']"
        success_msg: containerd.io is installed.
        fail_msg: containerd.io is not installed.

    - name: Assert docker-buildx-plugin is installed
      ansible.builtin.assert:
        that: "'docker-buildx-plugin' in ansible_facts['packages']"
        success_msg: docker-buildx-plugin is installed.
        fail_msg: docker-buildx-plugin is not installed.

    - name: Assert docker-compose-plugin is installed
      ansible.builtin.assert:
        that: "'docker-compose-plugin' in ansible_facts['packages']"
        success_msg: docker-compose-plugin is installed.
        fail_msg: docker-compose-plugin is not installed.

    - name: Get all the current user's groups
      ansible.builtin.shell:
        cmd: id -nG
      register: users_groups
      changed_when: false

    - name: Assert current user is in the docker group
      ansible.builtin.assert:
        that: "'docker' in users_groups.stdout"
        success_msg: Current user is in the docker group.
        fail_msg: Current user is not in the docker group.

    - name: Gather facts about services
      ansible.builtin.service_facts:
    - name: Assert docker.service is enabled and running
      ansible.builtin.assert:
        that:
          - "'docker.service' in ansible_facts['services']"
          - ansible_facts['services']['docker.service']['state'] == 'running'
          - ansible_facts['services']['docker.service']['status'] == 'enabled'
        success_msg: docker.service is enabled and running.
        fail_msg: docker.service is not enabled and running.

    - name: Assert containerd.service is enabled and running
      ansible.builtin.assert:
        that:
          - "'containerd.service' in ansible_facts['services']"
          - ansible_facts['services']['containerd.service']['state'] == 'running'
          - ansible_facts['services']['containerd.service']['status'] == 'enabled'
        success_msg: containerd.service is enabled and running.
        fail_msg: containerd.service is not enabled and running.
